package: pkg-config

slices:
  bin:
    essential:
      - libc6_libs
      - libglib2.0-0_libs
      - libdpkg-perl_libs
    contents:
      /usr/bin/pkg-config:
      /usr/bin/x86_64-pc-linux-gnu-pkg-config:
      /usr/share/aclocal/pkg.m4:
