bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_python", version = "1.6.1")
bazel_dep(name = "rules_distroless", version = "0.6.1")

apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")
apt.install(
    name = "trixie",
    lock = "//:trixie.lock.json",
    manifest = "//:trixie.yaml",
)
use_repo(apt, "trixie")

bazelisk_ext = use_extension(":bazelisk.bzl", "bazelisk_extension")
use_repo(bazelisk_ext, "bazelisk")
